version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: fam
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: fam
      POSTGRES_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
